# Generated by Django 5.0.1 on 2024-01-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_fotos_delete_escolha_delete_pergunta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
