# Generated by Django 5.0.1 on 2024-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_rename_fotos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
