# Generated by Django 5.0.1 on 2024-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_alter_foto_texto_alter_foto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='./static/images/'),
        ),
    ]
