# Generated by Django 5.0.1 on 2024-01-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0007_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='./lembrancas/fotos/static/images/'),
        ),
    ]
