# Generated by Django 5.0.1 on 2024-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0008_alter_foto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='teste',
            field=models.TextField(default='testando'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='./static/images/'),
        ),
    ]
