# Generated by Django 5.0.1 on 2024-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0010_remove_foto_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='teste',
            field=models.TextField(default=models.CharField(max_length=1000)),
        ),
    ]
