# Generated by Django 5.0.1 on 2024-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0011_foto_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='teste',
            new_name='mensagem',
        ),
    ]
