# Generated by Django 5.0.1 on 2024-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0012_rename_teste_foto_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='mensagem',
        ),
        migrations.AlterField(
            model_name='foto',
            name='texto',
            field=models.TextField(),
        ),
    ]
